kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: registry.git.duck.me.uk
      repo: registry.git.duck.me.uk/duck/duckdotuk
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

