image: docker:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.git.projectflower.eu

variables:
  CONTAINER_TEST_IMAGE: docker.git.projectflower.eu/luaduck/duckdotweb:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: docker.git.projectflower.eu/luaduck/duckdotweb:latest
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE --build-arg APP_VERSION=$CI_COMMIT_SHA .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - docker

release:
  type: release
  script:
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  environment:
      name: production
      url: https://duck.me.uk
  tags:
    - docker